### ISSUE TITLE
WYSIWYG Editor for static content

### ISSUE THREAD

**Issue by BrettMayson** [CompCamps/WebsiteArchive#5]
We should really use a WYSIWYG editor instead of static HTML pages. We don't want to lose that functionality when switching away from WordPress.

**Comment by rye761** [comment]
Since this essentially a hobby project, I'm open to the idea. However, I think we should consider what advantage we're really gaining by adding a WYSIWYG editor. It would be quite a bit simpler to just edit the markup on these files. I'm thinking of simplicity in the arch linux sense here. Everyone who needs to update these pages should understand enough HTML to do so and the pages aren't updated very frequently. To keep the system simple, it might be better to just leave them as static pages. I always find that I'm fighting WYSIWYG editors.

If you still don't agree, consider this: it may take significantly more time to implement the editor than the amount of time saved by the editor's use.

Like I said, I'm open to the idea, but I'm not sold. Looking forward to your thoughts.

**Comment by BrettMayson** [comment]
The main thing is that we are replacing WordPress. The only thing I got from other mentors when I proposed the idea was to make sure it was still easy to edit like WordPress was. We don't need anything overly fancy, but we shouldn't require all changes to be done through GitHub, especially for the non-logic code.

**Comment by rye761** [comment]
I guess if that something that the other mentors want then we can look to include it but I still think it is a relatively low priority item for the reasons I mentioned above.

**Comment by BrettMayson** [comment]
Closing as discussed at the March 3rd, 2019 meeting
